# Use a slim Python image for the frontend
FROM python:3.11-slim

# Install system dependencies for PDF processing (LibGL for OpenCV, etc.)
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install uv using the official installer script
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install Python dependencies
COPY pyproject.toml requirements.txt ./

# Copy your application code
COPY ./src ./src

# Install Python dependencies
RUN uv pip install --system -r requirements.txt --no-cache-dir

# Expose Streamlit's default port
EXPOSE 8501 8001

# Healthcheck to tell Docker when the UI is actually "Up"
HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health || exit 1


# Run with headless settings for Docker
CMD ["python", "-m", "streamlit", "run", "src/app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true", \
     "--server.enableCORS=false",\
      "--server.enableXsrfProtection=false",\
     "--browser.gatherUsageStats=false"]
